name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Start timer
      id: timer
      run: echo "CI/CD started at $(date +%s)" > start_time.txt

    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run JaCoCo tests and check code coverage
      run: |
        mvn jacoco:report
        bash <(curl -s https://codecov.io/bash) -t your_codecov_token
      continue-on-error: true

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco

    - name: Verify JaCoCo coverage
      run: |
        mvn jacoco:report
        COVERAGE=$(grep -oP 'Total.*?(\d+)%' target/site/jacoco/jacoco.csv | grep -oP '\d+')
        if [ "$COVERAGE" -lt 80 ]; then
          echo "Code coverage is below 80%: $COVERAGE%"
          exit 1
        fi

    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle
      continue-on-error: true

    - name: Verify Checkstyle
      run: |
        ERRORS=$(mvn checkstyle:checkstyle | grep -oP 'Total.*?(\d+) errors' | grep -oP '\d+')
        if [ "$ERRORS" -ne 0 ]; then
          echo "Checkstyle found errors: $ERRORS"
          exit 1
        fi

    - name: Run SpotBugs
      run: mvn spotbugs:spotbugs
      continue-on-error: true

    - name: Verify SpotBugs
      run: |
        CRITICALS=$(mvn spotbugs:spotbugs | grep -oP 'Total.*?(\d+) critical' | grep -oP '\d+')
        if [ "$CRITICALS" -ne 0 ]; then
          echo "SpotBugs found critical issues: $CRITICALS"
          exit 1
        fi

    - name: End timer and check duration
      run: |
        END_TIME=$(date +%s)
        START_TIME=$(cat start_time.txt | grep -oP '\d+')
        DURATION=$((END_TIME - START_TIME))
        if [ "$DURATION" -gt 180 ]; then
          echo "CI/CD process took longer than 3 minutes: $DURATION seconds"
          exit 1
        fi
